[2025-09-15T06:45:56.405+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-15T06:34:35.208642+00:00 [queued]>
[2025-09-15T06:45:56.413+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-15T06:34:35.208642+00:00 [queued]>
[2025-09-15T06:45:56.413+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2025-09-15T06:45:56.514+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): gold_saved_transform> on 2025-09-15 06:34:35.208642+00:00
[2025-09-15T06:45:56.536+0000] {standard_task_runner.py:57} INFO - Started process 32060 to run task
[2025-09-15T06:45:56.542+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spotify_saved_tracks_etl_pipeline', 'gold_saved_transform', 'manual__2025-09-15T06:34:35.208642+00:00', '--job-id', '806', '--raw', '--subdir', 'DAGS_FOLDER/spotify_saved_dag.py', '--cfg-path', '/tmp/tmp73u_dxsi']
[2025-09-15T06:45:56.547+0000] {standard_task_runner.py:85} INFO - Job 806: Subtask gold_saved_transform
[2025-09-15T06:45:56.592+0000] {task_command.py:415} INFO - Running <TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-15T06:34:35.208642+00:00 [running]> on host 0d0cd054d690
[2025-09-15T06:45:56.663+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_saved_tracks_etl_pipeline' AIRFLOW_CTX_TASK_ID='gold_saved_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T06:34:35.208642+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-15T06:34:35.208642+00:00'
[2025-09-15T06:45:56.684+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etl/db_utils.py", line 11, in run_sql_scripts
    cur.execute(sql)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "s"
LINE 8:  s.track_id,
         ^

[2025-09-15T06:45:56.697+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_saved_tracks_etl_pipeline, task_id=gold_saved_transform, execution_date=20250915T063435, start_date=20250915T064556, end_date=20250915T064556
[2025-09-15T06:45:56.713+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 806 for task gold_saved_transform (missing FROM-clause entry for table "s"
LINE 8:  s.track_id,
         ^
; 32060)
[2025-09-15T06:45:56.724+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-15T06:45:56.742+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
